# Generated by Django 5.1 on 2024-09-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('view', models.SmallIntegerField(default=0)),
                ('view_user', models.ManyToManyField(related_name='articles_viewed', to='users.user')),
                ('wirter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles_written', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ManyToManyField(to='users.user')),
            ],
        ),
    ]
