# Generated by Django 5.1 on 2024-09-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_article'),
        ('users', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='wirter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_written', to='users.user'),
        ),
    ]
